apiVersion: apps/v1
kind: Deployment
metadata:
  name: recruitment-app-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: recruitment
  template:
    metadata:
      labels:
        app: recruitment
    spec:
      containers:
        - name: recruitment-app-container
          image: shubha20/recruitment-app-project_app:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "150m"
          env:
          - name: MONGO_URI
            value: "mongodb://recruitmentuser:recruit123@mongodb-service:27017/recruitment_system?authSource=recruitment_system"
          - name: DB_NAME
            value: "hr_system"

---
apiVersion: v1
kind: Service
metadata:
  name: recruitment-service
spec:
  selector:
    app: recruitment
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort        