version: "3.9"

services:

  app:
    build: .
    container_name: recruitment-app
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - frontend-net
    expose:
      - "3000"

  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - frontend-net
      - backend-net

networks:
  frontend-net:
  backend-net:

volumes:
  mongo-data:
